#!/bin/sh

if [ -d /mnt/us/localization ]
then
   mount --bind /opt/amazon/ebook/booklet_loc /opt/amazon/ebook/booklet
   mount --bind /opt/amazon/ebook/lib_loc /opt/amazon/ebook/lib
   mount --bind /opt/amazon/ebook/img/ui_loc /opt/amazon/ebook/img/ui
   mount --bind /opt/amazon/ebook/config_loc/msp_prefs /opt/amazon/ebook/config/msp_prefs
   if [ -s /opt/amazon/ebook/config/browser_prefs ]
   then
     mount --bind /opt/amazon/ebook/config_loc/reader.conf /opt/amazon/ebook/config/reader.conf
     mount --bind /opt/amazon/ebook/config_loc/browser_prefs /opt/amazon/ebook/config/browser_prefs
   fi
fi
